### ISSUE TITLE
Issue with initialization of the repository

### ISSUE THREAD

**Issue by MrMoyaert** [tiredofit/docker-restic#13]
### Summary

I have been testing with this container since a day or 2 since I want to use the Zabbix integration.
Initially I got it working in a test setup, and I was migrating it to my production environment
I deleted everything (all the persistent folders on my host) and copy pasted my final docker compose file to my production environment.
Now I'm running into the issue that the log is stating that there is no repository know (error 10), so it seems like its not initializing.
I tried initializing it manually, but then i get error 12, password not correct.
I'm trying to use backup-now to run test backups (whish was working before on my test setup)

### Steps to reproduce

- Deploy the docker compose file (see below)
- log into the container and run a manual backup (backup-now)

```
services:
  restic-app:
    image: tiredofit/restic
    uts: host
    container_name: restic-test
    volumes:
      - /docker/restic-test/cache:/cache
      - /docker/restic-test/config:/config
      - /docker/restic-test/logs:/logs
      - /docker/restic-test/scripts:/scripts
      - /backups-test:/repository
      - /backups-test/tmp-for-restore:/tmp-for-restore


      #Folder to Backup
      - /docker:/rootfs/docker:ro
      - /home/ruben:/rootfs/home/ruben:ro
      - /etc/zabbix:/rootfs/etc/zabbix:ro
    environment:
      - TIMEZONE=Europe/Brussels
      - CONTAINER_NAME=HomeServer

      - MODE=BACKUP,CHECK,PRUNE

      - CACHE_PATH=/cache
      - CONFIG_PATH=/config
      - LOG_PATH=/logs
      - LOG_TYPE=FILE


      - DEFAULT_BACKUP_ENABLE_CLEANUP=TRUE
      - DEFAULT_BACKUP_REPOSITORY_PASS=<DELETED>

      - BACKUP01_SNAPSHOT_NAME=HomeServer
      - BACKUP01_SNAPSHOT_PATH=/rootfs
      - BACKUP01_REPOSITORY_PATH=/repository
      - BACKUP01_SNAPSHOT_EXCLUDE=.snapshots,cache,NOBACKUP_db
      - BACKUP01_SNAPSHOT_BEGIN=0400
      - BACKUP01_SNAPSHOT_INTERVAL=1440

      - DEFAULT_CHECK_ARGS= >-
        --read-data-subset=10%
      - DEFAULT_CHECK_REPOSITORY_PATH=/repository
      - DEFAULT_CHECK_REPOSITORY_PASS=<DELETED>

      - CHECK01_BEGIN=0515
      - CHECK01_INTERVAL=1440


      - DEFAULT_PRUNE_REPOSITORY_PATH=/repository
      - DEFAULT_PRUNE_REPOSITORY_PASS=<DELETED>
      
      - PRUNE01_BEGIN=0500
      - PRUNE01_INTERVAL=1440

      - ZABBIX_SERVER_ACTIVE=192.168.1.20
    restart: unless-stopped
```

### What is the expected *correct* behavior?

That the backup-now just works on the first try

### Relevant logs and/or screenshots

```
[tiredofit/restic:1.2.25 22:43:39 /assets/restic/template-restic-backup] $ tail /logs/latest-backup-homeserver.log
### Backup Details
open repository

#### Error Log


Fatal: repository does not exist: unable to open config file: stat /repository/config: no such file or directory
Is there a repository at the following location?
/repository
```

![Image](https://github.com/user-attachments/assets/4d72bb06-a539-4650-a0f8-ec8fff9dc48b)

### Environment
- Image version / tag:  tiredofit/restic:latest
- Host OS: Ubuntu 24.04 LTS
